<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PropiedadSeeder extends Seeder
{
    public function run(): void
    {
        $propietarioId = 1;
        $fotos = json_encode([
            'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1000',
            'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1000',
        ]);

        $propiedades = [
            [
                'id_propietario' => $propietarioId,
                'tipo_propiedad_id' => 1,
                'titulo' => 'Casa de Campo Familiar',
                'descripcion' => 'Hermosa casa de campo con amplio jardín, ideal para familias que buscan tranquilidad y contacto con la naturaleza. Cuenta con 4 habitaciones, sala de estar, cocina equipada y chimenea.',
                'direccion' => 'Carretera a Dolores Hidalgo Km 8',
                'pais' => 'México',
                'estado_ubicacion' => 'Guanajuato',
                'ciudad' => 'San Miguel de Allende',
                'colonia' => 'Valle de Alcocer',
                'precio' => 28000.00,
                'habitaciones' => 4,
                'banos' => 3.0,
                'metros_cuadrados' => 250.00,
                'amueblado' => true,
                'anualizado' => false,
                'deposito' => 14000.00,
                'mascotas' => true,
                'estado_propiedad' => 'Disponible',
                'fotos' => $fotos,
                'email' => 'propietario@example.com',
                'telefono' => '4151234567',
            ],
            [
                'id_propietario' => $propietarioId,
                'tipo_propiedad_id' => 4,
                'titulo' => 'Loft Industrial Minimalista',
                'descripcion' => 'Loft estilo industrial en el corazón de San Miguel de Allende. Espacio abierto con techos altos, cocina americana y vistas espectaculares. Perfecto para profesionales.',
                'direccion' => 'Calle Corregidora 42',
                'pais' => 'México',
                'estado_ubicacion' => 'Guanajuato',
                'ciudad' => 'San Miguel de Allende',
                'colonia' => 'Centro Histórico',
                'precio' => 12500.00,
                'habitaciones' => 1,
                'banos' => 1.0,
                'metros_cuadrados' => 75.00,
                'amueblado' => true,
                'anualizado' => false,
                'deposito' => 6250.00,
                'mascotas' => false,
                'estado_propiedad' => 'Disponible',
                'fotos' => $fotos,
                'email' => 'propietario@example.com',
                'telefono' => '4151234567',
            ],
            [
                'id_propietario' => $propietarioId,
                'tipo_propiedad_id' => 1,
                'titulo' => 'Casa Rústica de Piedra',
                'descripcion' => 'Encantadora casa rústica construida en piedra, con acabados artesanales y patio interior. Alberca privada y terraza con vista al campo. Ubicación exclusiva.',
                'direccion' => 'Camino a Los Rodríguez 15',
                'pais' => 'México',
                'estado_ubicacion' => 'Guanajuato',
                'ciudad' => 'San Miguel de Allende',
                'colonia' => 'Colonia Atascadero',
                'precio' => 32000.00,
                'habitaciones' => 3,
                'banos' => 2.0,
                'metros_cuadrados' => 190.00,
                'amueblado' => true,
                'anualizado' => true,
                'deposito' => null,
                'mascotas' => true,
                'estado_propiedad' => 'Disponible',
                'fotos' => $fotos,
                'email' => 'propietario@example.com',
                'telefono' => '4151234567',
            ],
            [
                'id_propietario' => $propietarioId,
                'tipo_propiedad_id' => 2,
                'titulo' => 'Depa Céntrico Ejecutivo',
                'descripcion' => 'Departamento moderno en zona céntrica, cerca de restaurantes, bancos y transporte público. Edificio con seguridad 24 hrs, estacionamiento y roof garden.',
                'direccion' => 'Av. Independencia 120',
                'pais' => 'México',
                'estado_ubicacion' => 'Guanajuato',
                'ciudad' => 'San Miguel de Allende',
                'colonia' => 'Zona Centro',
                'precio' => 15000.00,
                'habitaciones' => 2,
                'banos' => 1.0,
                'metros_cuadrados' => 85.00,
                'amueblado' => true,
                'anualizado' => false,
                'deposito' => 7500.00,
                'mascotas' => false,
                'estado_propiedad' => 'Disponible',
                'fotos' => $fotos,
                'email' => 'propietario@example.com',
                'telefono' => '4151234567',
            ],
            [
                'id_propietario' => $propietarioId,
                'tipo_propiedad_id' => 3,
                'titulo' => 'Cabaña de Campo Confortable',
                'descripcion' => 'Acogedora cabaña rodeada de naturaleza, ideal para descansar. Cuenta con fogata exterior, hamacas y senderos peatonales. A 15 min del centro.',
                'direccion' => 'Camino Viejo a Dolores 8',
                'pais' => 'México',
                'estado_ubicacion' => 'Guanajuato',
                'ciudad' => 'San Miguel de Allende',
                'colonia' => 'Los Rodríguez',
                'precio' => 19000.00,
                'habitaciones' => 2,
                'banos' => 2.0,
                'metros_cuadrados' => 110.00,
                'amueblado' => true,
                'anualizado' => false,
                'deposito' => 9500.00,
                'mascotas' => true,
                'estado_propiedad' => 'Disponible',
                'fotos' => $fotos,
                'email' => 'propietario@example.com',
                'telefono' => '4151234567',
            ],
            [
                'id_propietario' => $propietarioId,
                'tipo_propiedad_id' => 2,
                'titulo' => 'Depa Rústico Con Encanto',
                'descripcion' => 'Pequeño departamento con acabados rústicos y ubicación privilegiada en el barrio más tradicional de SMA. Ideal para parejas o nómadas digitales.',
                'direccion' => 'Calle de San Francisco 23',
                'pais' => 'México',
                'estado_ubicacion' => 'Guanajuato',
                'ciudad' => 'San Miguel de Allende',
                'colonia' => 'Barrio de San Juan de Dios',
                'precio' => 14000.00,
                'habitaciones' => 1,
                'banos' => 1.0,
                'metros_cuadrados' => 65.00,
                'amueblado' => true,
                'anualizado' => false,
                'deposito' => 7000.00,
                'mascotas' => false,
                'estado_propiedad' => 'Disponible',
                'fotos' => $fotos,
                'email' => 'propietario@example.com',
                'telefono' => '4151234567',
            ],
            [
                'id_propietario' => $propietarioId,
                'tipo_propiedad_id' => 1,
                'titulo' => 'Residencia de Lujo Rústica',
                'descripcion' => 'Espectacular residencia con diseño rústico contemporáneo. 5 recámaras, alberca infinita, jardín privado y vistas panorámicas al campo de golf.',
                'direccion' => 'Paseo de los Golfistas 450',
                'pais' => 'México',
                'estado_ubicacion' => 'Guanajuato',
                'ciudad' => 'San Miguel de Allende',
                'colonia' => 'Club de Golf',
                'precio' => 45000.00,
                'habitaciones' => 5,
                'banos' => 4.0,
                'metros_cuadrados' => 380.00,
                'amueblado' => true,
                'anualizado' => true,
                'deposito' => null,
                'mascotas' => true,
                'estado_propiedad' => 'Disponible',
                'fotos' => $fotos,
                'email' => 'propietario@example.com',
                'telefono' => '4151234567',
            ],
        ];

        DB::table('propiedades')->insert($propiedades);
    }
}
